### ISSUE TITLE
Chapter 3: Data Ethics - Book - Deep Learning for Coders With Fastai and Pytorch Ai Applications

### ISSUE THREAD

**Issue by JeremyLoh** [JeremyLoh/ml#7]
# Tasks
- [x] Read the article “What Happens When an Algorithm Cuts Your Healthcare” https://www.theverge.com/2018/3/21/17144260/healthcare-medicaid-algorithm-arkansas-cerebral-palsy
- [x] Research to find out more about YouTube’s recommendation system and its societal impacts
    - [x] 10:40 / 42:42  Stanford Seminar - Algorithmic Extremism: Examining YouTube's Rabbit Hole of Radicalization  (Jan 8 2020) https://www.youtube.com/watch?v=K_MGWHiEeMk 
- [x] 0 / 18 page - Read the paper “Discrimination in Online Ad Delivery”. Do you think Google should be considered responsible for what happened to Dr. Sweeney? What would be an appropriate response? https://dl.acm.org/doi/10.1145/2460276.2460278 -> PDF link https://dl.acm.org/doi/pdf/10.1145/2460276.2460278
- [x] 34:00 / 52:31 Trevor Noah on the Future of Entertainment and AI https://www.youtube.com/watch?v=4ZD-ZIS2CfU

## Current Page: 246

Page 185
What is Ethics?
- Well founded standards of right and wrong that prescribe what humans should do
- The study and development of one's ethical standards

No right or wrong answers, it is complicated and context dependent, involves perspectives of many stakeholders

Page 186

### Key Examples for Data Ethics
3 specific examples that illustrate 3 common ethical issues in tech
- **Recourse processes** - Arkansas's buggy healthcare algorithms left patients stranded
- **Feedback loops** - YouTube's recommendation system helped unleash a conspiracy theory boom
- **Bias** - When a traditionally African-American name is searched for on Google, it displays ads for criminal background checks

### Bugs and Recourse: Buggy algorithm used for healthcare benefits (Page 187)
https://www.theverge.com/2018/3/21/17144260/healthcare-medicaid-algorithm-arkansas-cerebral-palsy
Software was used in over half of US states to determine how much healthcare people receive

In Arkansas, the algorithm caused hundreds of people (many with severe disabilities) to have their healthcare drastically cut

### Feedback Loops: YouTube's recommendation system
Feedback loops can happen when your model is controlling the next round of data you get
The data that is returned becomes flawed by the software itself
e.g. YouTube recommendation algorithm is designed to optimize watch time. Recommendation systems are predicting what content people will like, but they also have a lot of power in determining what content people even see

### Bias: Professor Latanya Sweeney "Arrested"
Googling her name resulted in advertisements saying "Latanya Sweeney, Arrested?"

## Measurement Bias (page 219)
Measurement bias occurs when our models makes mistakes because we are measuring the wrong thing, or measuring it in the wrong way, or incorporating that measurement into the model inappropriately

e.g. Using historical electronic health record (EHR) data, what factors are most predictive of stroke?
- From the model, these were the top predictors
    - Prior stroke
    - Cardiovascular disease
    - Accidental injury
    - Benign breast lump
    - Colonoscopy
    - Sinusitis
But only the top 2 have anything to do with a stroke!
We haven't measured stroke, which occurs when a region of the brain is denied oxygen due to an interruption in the blood supply
What we have measured is who had symptoms, went to a doctor, got the appropriate tests, and received a diagnosis of stroke

## Aggregation bias
When models do not aggregate data in a way that incorporates all of the appropriate factors, or when a model does not include the necessary interaction terms
e.g. particularly occur in medical settings. e.g. diabetes is often treated based on simple univariate statistics and studies involving small groups of heterogeneous people. Does not take into account different genders or ethnicities

## Representation bias
e.g. occupations where there are more males than females and vice versa.

Machine learning is often implemented in practice not because it leads to better outcomes, but because it is cheaper and more efficient.

The privileged are processed by people. whereas the poor are processed by algorithms

Page 232

Another useful resource from the Markkula Center is its Conceptual Frameworks in Technology and Engineering Practice. This considers how different foundational ethical lenses can help identify concrete
issues, and lays out the following approaches and key questions:

### The rights approach
Which option best respects the rights of all who have a stake?

### The justice approach
Which option treats people equally or proportionately?

### The utilitarian approach
Which option will produce the most good and do the least harm?

### The common good approach
Which option best serves the community as a whole, not just
some members?

### The virtue approach
Which option leads me to act as the sort of person I want to be?

Page 238

In philosophy, and especially philosophy of ethics, this is one of the most effective tools: first, come up with a process, definition, set of questions, etc., which is designed to resolve a problem. Then try to
come up with an example in which that apparent solution results in a proposal that no one would consider acceptable. This can then lead to a further refinement of the solution
